### ISSUE TITLE
Stripping gameplay out to bare essentials

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unity-UltimateGloveBall#8]
We require to strip out the gloveball gameplay functionalties on the avatars and in scene in order to integrate our Interaction SDK based product. 

I have managed to succesfully remove all the balls, obstacles etc in scene related to Gloveball but main issue is how we can revert the avatar from having the gloves (we dont need them). 

Our project centres around hand tracking in multiplayer and the players being able to interact with placed objects in scene. I see that there is a CameraRig prefab in the app folder so hopefully adding the iteraction prefabs to this to match my current OVRCamerarig setup will work. So now mainly I just need to know how to remove the gloves from players.

Thanks

**Comment by jasonmeisel** [comment]
You'd need to prevent the gloves from being spawned in `ArenaPlayerSpawningManager.SpawnPlayer`, and then also remove any references to those gloves throughout the codebase.

> Our project centres around hand tracking in multiplayer and the players being able to interact with placed objects in scene.

We've actually just released a new showcase that might be a better starting point for you. It supports exactly that scenario, using Interaction SDK for the interactions. Check it out here: https://github.com/oculus-samples/Unity-Decommissioned

**Comment by owlandfox** [comment]
Oh this does look cool! Thanks ill check that out

**Comment by owlandfox** [comment]
Took a look at the other project and as much as it looks good we opted to stay with Gloveball due to the spectator functionality - OUr app is a live music performance experience so having the option for players to join as co-players or as a simple spectator is great for us. We managed to strip out the gloves and all code and succesfully have multiplayers appearing on scene with a couple issues -

1. Voip does not seem to be working / connecting. I have double checked the Voip Photon app ID and it is correct. IN the Photon dashbaord i can see that the Realtime App ID is getting traffic but the Voice App is not. I made sure not to remove anything Voip related when removing the gloves so not sure whats happened here.

2. Our scene contains multiple Unity sliders, buttons, toggles and general UI that we need to be synced across all players scenes. Im assuming this needs to be done with the Unity Netcode that was used for syncing the gloves and balls across players individual scenes but if you could point us in the correct direction for adding our UI that would be great :)

**Comment by AlexThiv** [comment]
Hi,

We are glad that you see value in Gloveball and the spectator mode.

1) I would start by looking if the [VOIPController ](https://github.com/oculus-samples/Unity-UltimateGloveBall/blob/main/Packages/com.meta.multiplayer.netcode-photon/Core/VoipController.cs) is spawning the voice recorder. Checking that JoinPhotonVoiceRoom() goes through as well as calling StartVoip.

2) In order to keep the UI in sync you would want to use network variables that are updated as they are used. You might need to set it up in a way so that no 2 players can modify them at the same time either with host authority/request for a change or it can also be a free for all where it simply takes the latest update. Decoupling the visual from the value might also help, where while modifying a slider, for example, it shows the action and applies the action the local user is doing and update the network variable. And Only when released it would take the actual last set network value.
